### ISSUE TITLE
Losing changes when switching to another active ("Working Files") file.

### ISSUE THREAD

**Issue by ghost** [roicos/brackets-changing-tags#1]
Hi!

I discovered an issue, If I make some changes and switch to another file in "Working Files" before saving the file the changes are being removed.
As default (or when the plugin is disabled) the changes stay as they are when I switch to another file and I can undo, redo and save after switching back to the document.

**Comment by roicos** [comment]
Thanks for your feedback! 
Could you attach files you are working on when the bug appears?
Would be great if you also briefly describe the changes being removed.

**Comment by ghost** [comment]
Hi,

To recreate the issue, I disabled all other extensions, made two simple files, one HTML and one CSS.
1. If I change something in the HTML file (don't save it) and switch to the CSS file I can go back and undo, redo and save the changes I made. (A dot mark appears on the left of my HTML file name. You can see it in the second screenshot.)
2. If I change something in the CSS file (for example changed "50" to "10") (don't save it) and switch to the HTML file, there is no dot mark on the left of CSS file name, if I go back the "50" is still "50" and all the undo and redo history is also gone.

This happen with other CSS files in other projects as well.
Edit: Also it does not have to be a number, any change in the CSS disappears if I do not save it before switching to a different file.  

![screenshot 1](https://cloud.githubusercontent.com/assets/3663795/17008177/9dbc8b0e-4f0c-11e6-8908-96f67bcced6d.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/3663795/17008183/a0afa30a-4f0c-11e6-801b-efcb6d8d6884.png)

**Comment by roicos** [comment]
Thanks for detalization! Now I see this bug too and trying to figure out what happens.

**Comment by roicos** [comment]
Please, update the extension.

**Comment by ghost** [comment]
Hi,
Everything is working alright now. :)
You can close the issue.
Thank you!
